apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-core-app-sets
  namespace: argocd
spec:
  destination:
    namespace: 'argocd'
    name: 'in-cluster'
  source:
    path: application-sets/
    repoURL: https://github.com/AixaCarrizo/workshop-argocd-applications.git
    targetRevision: main
    directory: 
      recurse: true
      exclude: '{*/values/*.yaml,*/manifests/*}'
  project: test-argocd-admin
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true